spring:
  threads:
    virtual:
      enabled: true #To enable virtual threads in Spring Boot 3.2 we just need to set this property
  application:
    name: myCofre-server
  datasource:
    url: 'jdbc:mysql://server.mycofre.com:3306/mycofre?serverTimezone=UTC'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: '${MYCOFRE_DB_USER}'
    password: '${MYCOFRE_DB_PASS}'
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000
  mail:
    host: smtp.postmarkapp.com
    port: 587
    username: '${MYCOFRE_SMTP_TOKEN}'
    password: '${MYCOFRE_SMTP_TOKEN}'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    basename: messages
    encoding: UTF-8

  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog-master.xml'
  lifecycle:
    timeout-per-shutdown-phase: "20s"
  web:
    locale: es
    locale-resolver: fixed

springdoc:
  api-docs:
    path: /myCofre-api/docs
  swagger-ui:
    path: /myCofre-api/docs/swagger-ui-custom.html

logging:
  level:
    root: DEBUG
    liquibase: INFO
    myCofre.server.config.RestExceptionHandler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
  file:
    name: logs/myCofre.log
    max-size: 10MB
    max-history: 7

