spring:
  threads:
    virtual:
      enabled: true #To enable virtual threads in Spring Boot 3.2 we just need to set this property
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://PMYSQL166.dns-servicio.com:3306/9628284_myCofre?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYCOFRE_DB_USER}
    password: ${MYCOFRE_DB_PASS}
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000
  mail:
    host: smtp.postmarkapp.com
    port: 587
    username: ${MYCOFRE_SMTP_TOKEN}
    password: ${MYCOFRE_SMTP_TOKEN}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

springdoc:
  api-docs:
    path: /myCofre-api/docs
  swagger-ui:
    path: /myCofre-api/docs/swagger-ui-custom.html

logging.level:
  root: DEBUG
  liquibase: INFO