server:
  port: 443
  shutdown: graceful
  ssl:
    key-store: /etc/letsencrypt/live/server.mycofre.com/mycofre.p12
    key-store-password: '${MYCOFRE_KEYSTORE_PASS}'
    key-store-type: PKCS12
    key-alias: mycofre
    enabled: true
  clienturl: https://www.mycofre.com
