server:
  port: 9000
  # graceful shutdown makes sure we have time to finnish any ongoing rest requests before terminating
  # default value will be 30s before terminating
  shutdown: graceful
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pass123
    key-store-type: PKCS12
    key-alias: mycofre

spring:
  threads:
    virtual:
      enabled: true #To enable virtual threads in Spring Boot 3.2 we just need to set this property
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://PMYSQL166.dns-servicio.com:3306/9628284_myCofre?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myCofreAdmin
    password: 9C4675BB9Aab
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

springdoc:
  api-docs:
    path: /myCofre-docs
  swagger-ui:
    path: /myCofre-docs/swagger-ui-custom.html

logging.level:
  root: DEBUG
  liquibase: INFO